apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    helm.sh/chart: {{ include "elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  serviceName: {{ include "elasticsearch.fullname" . }}
  replicas: {{ .Values.master.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default "5" }}
  podManagementPolicy: {{ .Values.podManagementPolicy | default "Parallel" }}
  updateStrategy:
    type: {{ .Values.master.strategyType | default "OnDelete" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: master
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/common-cm.yaml") . | sha256sum }}
{{- if .Values.master.annotations }}
{{ toYaml .Values.master.annotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: master
    spec:
      serviceAccountName: {{ include "elasticsearch.fullname" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      initContainers:
      {{- if .Values.virtualMemory.enabled }}
      - name: sysctl
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sysctl
          - -w
          - vm.max_map_count={{ .Values.virtualMemory.maxMapCount | default 262144 }}
        securityContext:
          privileged: true
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          env:
            - name: ES_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.cluster.name
            - name: ES_NODE_NAME
              value: ${HOSTNAME}
            - name: ES_NODE_MASTER
              value: "true"
            - name: ES_RAM_PERCENTAGE
              value: {{ .Values.master.ramPercentage | quote }}
            - name: ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.discovery.zen.ping.unicast.hosts
            - name: ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.discovery.zen.minimum.master.nodes
            - name: ES_GATEWAY_RECOVER_AFTER_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.recover_after_data_nodes
            - name: ES_GATEWAY_EXPECTED_DATA_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.expected_data_nodes
            - name: ES_GATEWAY_RECOVER_AFTER_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" . }}
                  key: es.gateway.recover_after_time
          {{- range $key, $value := .Values.common.env }}
            - name: {{ $key | upper | replace "." "_" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "elasticsearch.fullname" $ }}
                  key: {{ $key }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/kill", "-15", "1"]
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
            initialDelaySeconds: 300
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
              readOnly: false
            - name: settings
              mountPath: /usr/share/elasticsearch/config/elasticsearch_custom.yml
              subPath: elasticsearch_custom.yml
              readOnly: true
          resources:
{{ toYaml .Values.master.resources | indent 12 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "elasticsearch.fullname" . }}-master
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: settings
        configMap:
          name: {{ template "elasticsearch.fullname" . }}
          items:
            - key: es.settings
              path: elasticsearch_custom.yml
    {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
      {{- if .Values.master.affinity }}
        {{- with .Values.master.affinity }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "elasticsearch.name" . }}
              - key: app.kubernetes.io/component
                operator: In
                values:
                - master
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "elasticsearch.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - master
              topologyKey: failure-domain.beta.kubernetes.io/zone
      {{- end }}
    {{- with .Values.master.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.master.provisioner }}
      storageClassName: {{ include "elasticsearch.fullname" . }}-master
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.master.size }}
  {{- end }}
