{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opentelemetry-operator.serviceAccountName" . }}
  labels:
{{ include "opentelemetry-operator.labels" . | indent 4 }}
{{- end -}}
