# Default values for opentelemetry-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/opentelemetry/opentelemetry-operator
  tag: v0.0.2
  pullPolicy: IfNotPresent

crd:
  install: true

openTelemetryCollector:
  # Specifies whether openTelemetryCollector resource should be created
  enabled: false
  # Empty values for keys should use ~ or {} to preserve the key when it is templated into the resource.
  # Helm drops empty keys and this modifies the result when it is transformed into the final resource.
  config:
    receivers:
      otlp:
        protocols:
          grpc: ~
    processors:
      queued_retry: {}
    exporters:
      logging: {}
    extensions:
      health_check: {}
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [queued_retry]
          exporters: [logging]

  # image:
  #   repository: otel/opentelemetry-collector
  #   tag: ~
  # mode: Deployment
  # args: {}
  # ports: []
  # replicas: ~
  # serviceAccount: ~
  # volumes: []
  # volumeMounts: []

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  clusterRole: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}

securityContext: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
