{{- if .Values.secretsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snappass.fullname" . }}
  labels:
{{ include "snappass.labels" . | indent 4 }}
type: Opaque
stringData:
  secretKey: {{ .Values.config.secretKey | default "Secret Key" | quote }}
  {{- if .Values.config.redisUrl }}
  redisUrl: {{ .Values.config.redisUrl | default "redis://username:password@localhost:6379/0" | quote }}
  {{- end}}
{{- end }}
