apiVersion: v2
description: A Helm chart for Kubernetes SecretUpdater
name: k8s-secret-updater
version: 2.2.0
icon: "https://github.com/fairfaxmedia/k8s-secret-updater"
maintainers:
  - name: Fairfax Media Operations
    email: github@fairfaxmedia.com.au
