awsDefaultRegion: "ap-southeast-2"
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: fairfaxmedia/k8s-secret-updater
  tag: latest
  pullPolicy: Always
service:
  name: secret-updater
  containerPort: 80
  probePath: "/internal/health"
serviceAccount:
  create: false
ingress:
  name: secret-updater
  containerPort: 80
  host: secret-updater.example.com
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: internal
    dns.alpha.kubernetes.io/internal: secret-updater.example.com
secretupdater:
  host: "0.0.0.0"
  port: "80"
  authMethod: "saml"
confidant:
  debug: "false"
  webhookUsername: "webhookusername"
  webhookPassword: "someSecretPasswordHere"
  serverAuthKey: "some_key_here"
  request:
    backoff: 1
    timeout: 5
    retries: 0
saml:
  confidantUrlRoot: "https://confidant.example.com/"
apiVersionOverrides:
  ingress: "networking.k8s.io/v1"
securityContext:
  runAsNonRoot: false
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsGroup: 10001
