name: zalenium
version: 0.0.2
appVersion: 3.141.59
description: Chart for deploying Zalenium
sources:
  - https://github.com/zalando/zalenium
maintainers:
  - name: diemol
    email: diemol@gmail.com
  - name: Fairfax Media Operations
    email: github@fairfaxmedia.com.au
engine: gotpl
